### ISSUE TITLE
Run selected text coming to core editor in v1.3.0

### ISSUE THREAD

**Issue by Tyriar** [formulahendry/vscode-terminal#1]
Just a heads up (I couldn't find your Twitter account), the [ability to run selected text in the integrated terminal](https://github.com/Microsoft/vscode/issues/7034) is coming to the core editor in v1.3.0. You can check it out in the Insiders build https://code.visualstudio.com/insiders

**Comment by formulahendry** [comment]
Thanks Daniel for the heads up!
