### ISSUE TITLE
bash on win10 can't use "open in integrate terminal"

### ISSUE THREAD

**Issue by imgwho** [formulahendry/vscode-terminal#10]
oops...the same problem persists....
when i use "open in integrate terminal"  appear:
```
cd "e:\practice\test\fun"
wuv@wuv:/mnt/e/practice/test$ cd "e:\practice\test\fun"
bash: cd: e:\practice\test\fun: No such file or directory
```
![as the picture shows](https://i.loli.net/2017/07/22/5973614b3be4d.png)
Thank you very much for your reply!

**Comment by formulahendry** [comment]
@imgwho I have just published a new fix, please have a try.

**Comment by imgwho** [comment]
@formulahendry  awesome!!!!!  the version 0.10 is correct ,thx  very  very  very  much !!~~
