### ISSUE TITLE
Can't use the Command-shift-P

### ISSUE THREAD

**Issue by amansanghvi** [formulahendry/vscode-terminal#11]
Hey, Command-shift-P is not working for me, so I can't past the code to install it. Is there another way to install it?

**Comment by formulahendry** [comment]
You could try this: https://code.visualstudio.com/docs/editor/extension-gallery#_install-an-extension or this: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix  (visx is here https://github.com/formulahendry/vscode-terminal/releases/tag/0.0.10)
