### ISSUE TITLE
Underscore is missing and not usable in Ubuntu 16.04

### ISSUE THREAD

**Issue by jpSimkins** [formulahendry/vscode-terminal#14]
I noticed this when trying to taint resources in Terraform but this is not limited to just Terraform.

I cannot use an underscore (`_`) in bash from within the terminal. I can open the OS terminal and run the command just fine. The issue appears to be with this plugin. 

Whenever I do try to type or paste a command with an underscore, it is replaced with a space and the command breaks.  In bash as a whole, I am unable to use underscores in the terminal window on my Ubuntu 16.04 box.

**Comment by formulahendry** [comment]
Hi @jpSimkins , how do you use this extension to run command? And could you have a screenshot?

**Comment by jpSimkins** [comment]
The command I am trying to run is:
```
terraform taint aws_security_group.allow_ssh
```

You can see from [this image](https://imgur.com/nnw32Wj), that all underscores are spaces. When I run the command, I get errors since the underscores are missing. No matter how I try to enter the command, typing or pasting, I am unable to get it to work. So I need to open my terminal and run the command from there. 

I open terminal by clicking the icon on the bottom right bar.

**Comment by formulahendry** [comment]
Hi @jpSimkins , you are uisng the VS Code built-in terminal. No relation of this extension. So closing it.
