### ISSUE TITLE
font aliasing feature

### ISSUE THREAD

**Issue by stalkov** [formulahendry/vscode-terminal#16]
I was wondering if it is possible to make the terminal text font display configurable, e.g. in the VSC configuration "workbench.fontAliasing": "antialiased." It is considerable easier for me to read in the editor with a dark theme with that setting. Thank you.

**Comment by formulahendry** [comment]
Hi @stalkov , this issue should be opened to VSCode repo. It is not related to this extension.

**Comment by stalkov** [comment]
Thank you.
