### ISSUE TITLE
Feature/request multiple terminals on the same panel.

### ISSUE THREAD

**Issue by bernalrs** [formulahendry/vscode-terminal#18]
Feature request: Add ability to display multiple terminals in the same panel. At the moment I am using tmux, however, would be nice to have this natively supported by the plugin. similar to Terminator terminal emulator  Thanks  

![Term](https://1.bp.blogspot.com/-VLzFONzYE2k/TrmFBHnOCtI/AAAAAAAAAAA/u7_g7VBD42I/s1200-w1200-h630-p-k-no-nu/2008-08-17-terminator.png)

**Comment by formulahendry** [comment]
No related to this extension. It is feature request for VS Code.
