### ISSUE TITLE
Can you add option to copy/paste data to terminal

### ISSUE THREAD

**Issue by pjangam** [formulahendry/vscode-terminal#5]
First of all great extension!!!
I don't have to open command prompt separately now.

Almost any terminal provides way to copy/paste data from it. 
Would be great if you could add this feature here.

Thanks!

**Comment by formulahendry** [comment]
Hi @pjangam , thanks for your feedback. Currently, the goal of this extension is to provide a convenient way to run commands of selected text or the whole file, not an interactive terminal. Moreover, this extension's function has merged into [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) and more support will be applied in Code Runner. Thus, you may have a try on built-in terminal of VS Code to see if it meets with your requirement.

**Comment by pjangam** [comment]
Great,

That clears up my confusion.

Thank you.
