### ISSUE TITLE
Why can't install for Mac？

### ISSUE THREAD

**Issue by ByWhy** [formulahendry/vscode-terminal#7]
![bo4z5xpk7r](https://cloud.githubusercontent.com/assets/13621465/26091600/d5694222-3a3e-11e7-85ac-860dc2e817bf.gif)

**Comment by formulahendry** [comment]
I believe it would be the VS Code issue. Could you install other extension?

**Comment by ByWhy** [comment]
您好谢谢您的解答。我的英语有点渣正在学习中，我看您在上海，我还是用中文给你说吧，见谅。也许是vs code版本问题，我今早更新了下，版本 1.12.2 ，其他插件都可以安装

**Comment by formulahendry** [comment]
I could install it on my MacBook. The extension installation has no difference for each extension. You need to report this issue to VS Code: https://github.com/microsoft/vscode

**Comment by ByWhy** [comment]
Thank you for your

**Comment by ByWhy** [comment]
您好，我想请问下，formulahendry.terminal-0.0.8这个文件夹是不是您那个插件的文件夹？以前我这上边能安装，我看还有历史文件夹，想通过手动删除的方式重新安装下

**Comment by formulahendry** [comment]
是的，可以试下

**Comment by ByWhy** [comment]
好的，谢谢您的回复

**Comment by ByWhy** [comment]
删除后，的确可以重新安装了

**Comment by formulahendry** [comment]
Great! Closing this issue then.
