### ISSUE TITLE
"Command not found" in .bash_profile for custom function

### ISSUE THREAD

**Issue by teknotica** [formulahendry/vscode-terminal#8]
Hello!

I'm finding the following error in my visual studio code terminal:

`bash: parse_git_branch: command not found`

![screen shot 2017-06-25 at 11 07 25](https://user-images.githubusercontent.com/354494/27515223-86d50e80-5996-11e7-8345-de7dcceaff0c.png)

I'm attaching the snippet of code it's referring to in my .bash_profile. It's been working ok in the OSX native terminal. It basically prints the current branch of the project.

![bash_profile](https://user-images.githubusercontent.com/354494/27515162-816df2aa-5995-11e7-971a-f833a9069642.png)

Thank you!

**Comment by teknotica** [comment]
I just restarted my computer and this issue has disappeared...

**Comment by formulahendry** [comment]
Closing then.
